---
language: node_js
node_js:
  - "10"
cache:
  directories:
    - ~/.npm
    - ~/.cache
sudo: false
install:
  - yarn install && yarn run bootstrap
script:
  - cd ${TRAVIS_BUILD_DIR}
  - yarn lint
  - yarn test
