---
language: node_js
node_js:
  - "node"
cache:
  directories:
    - ~/.npm
    - ~/.cache
sudo: false
install:
  - npm install && npm run bootstrap
script:
  - cd ${TRAVIS_BUILD_DIR}
  - npm run lint
  - npm test
